package org.treblereel.gwt.three4g.materials.parameters;

import jsinterop.annotations.JsPackage;
import jsinterop.annotations.JsType;
import jsinterop.base.JsPropertyMap;
import org.treblereel.gwt.three4g.renderers.webgl.WebGLProgram;

/**
 * @author Dmitrii Tikhomirov
 * Created by treblereel on 4/12/18.
 */
@JsType(isNative = true, namespace= JsPackage.GLOBAL, name="Object")
public class ShaderMaterialParameters extends MaterialParameters {

    /**
     * Define whether the material color is affected by global fog settings; true to pass fog uniforms to the shader.
     * Default is false.
     */
    public boolean fog;

    /**
     * Fragment shader GLSL code. This is the actual code for the shader. In the example above, the vertexShader
     * and fragmentShader code is extracted from the DOM; it could be passed as a string directly or loaded via
     * AJAX instead.
     */
    public String fragmentShader;

    /**
     * If set, this calls gl.bindAttribLocation to bind a generic vertex index to an attribute variable. Default is
     * undefined.
     */
    public String index0AttributeName;

    /**
     * Defines whether this material uses lighting; true to pass uniform data related to lighting to this shader. Default is false.
     */
    public boolean lights;

    /**
     * Controls wireframe thickness. Default is 1.
     * Due to limitations in the ANGLE layer, on Windows platforms linewidth will always be 1 regardless of the set value.
     */
    public float linewidth;

    /**
     * Defines whether the material uses morphTargets; true morphTarget attributes to this shader
     */
    public boolean morphTargets;

    /**
     * Defines whether the material uses morphNormals. Set as true to pass morphNormal attributes from the Geometry to the shader. Default is false.
     */
    public boolean morphNormals;

    /**
     * The compiled shader program associated with this material, generated by WebGLRenderer. You should not need to access this property.
     */
    public WebGLProgram program;

    /**
     * Define whether the material is rendered with flat shading. Default is false.
     */
    public boolean flatShading;

    /**
     * Define whether the material uses skinning; true to pass skinning attributes to the shader. Default is false.
     */
    public boolean skinning;

    /**
     * An object of the form:
     * { "uniform1": { value: 1.0 }, "uniform2": { value: 2 } } specifying the uniforms to be passed to the shader code; keys
     * are uniform names, values are definitions of the form
     * { value: 1.0 } where value is the value of the uniform. Names must match the name of the uniform, as defined in the
     * GLSL code. Note that uniforms are refreshed on every frame, so updating the value of the uniform will immediately
     * update the value available to the GLSL code.
     */
    public JsPropertyMap uniforms;

    /**
     * Define how the vertices are colored, by defining how the colors attribute gets populated. Possible values
     * are Constants.NoColors, Constants.FaceColors and Constants.VertexColors. Default is Constants.NoColors.
     */
    public Number vertexColors;

    /**
     * Vertex shader GLSL code. This is the actual code for the shader. In the example above, the vertexShader and fragmentShader code is extracted from the DOM; it could be passed as a string directly or loaded via AJAX instead.
     */
    public String vertexShader;

    /**
     * Render geometry as wireframe (using GL_LINES instead of GL_TRIANGLES). Default is false (i.e. render as flat
     * polygons).
     */
    public boolean wireframe;

    /**
     * Controls wireframe thickness. Default is 1.
     * Due to limitations in the ANGLE layer, on Windows platforms linewidth will always be 1 regardless of the set value.
     */
    public float wireframeLinewidth;
}
