import { Vector2 } from '../../../math/Vector2.js';
import { Matrix3 } from '../../../math/Matrix3.js';
import { Color } from '../../../math/Color.js';
import { Vector3 } from '../../../math/Vector3.js';


/**
* @typedef { { normalMap : {value : *},
*              normalScale : { value : Vector2},
*              diffuse : { value : Color},
*              opacity : { value : number},
*              uvTransform : { value : Matrix3},
*              uv2Transform : { value : Matrix3},
*              alphaMap : (undefined|{value: *}),
*              specularMap : (undefined|{value: *}),
*              envMap :(undefined|{value: *}),
*              flipEnvMap : { value : number},
*              reflectivity : { value : number},
*              refractionRatio : { value : number},
*              maxMipLevel : { value : number},
*              aoMapIntensity : { value : number},
*              aoMap : (undefined|{value: *}),
*              lightMap : (undefined|{value: *}),
*              lightMapIntensity : { value : number},
*              emissiveMap : (undefined|{value: *}),
*              bumpMap : (undefined|{value: *}),
*              bumpScale : { value : number},
*              displacementMap : (undefined|{value: *}),
*              displacementScale : { value : number},
*              displacementBias : { value : number},
*              roughnessMap : (undefined|{value: *}),
*              metalnessMap : (undefined|{value: *}),
*              gradientMap : (undefined|{value: *}),
*              fogDensity : { value : number},
*              fogNear : { value : number},
*              fogFar : { value : number},
*              fogColor : { value : Color},
*              ambientLightColor : (undefined|{ value : (Array|null)}),
*              lightProbe : { value : Array},
*              directionalLights : { value : Array, properties : { direction : *, color : *} },
*              directionalLightShadows : { value : Array, properties : { shadowBias : *, shadowNormalBias : *, shadowRadius : *, shadowMapSize : *} },
*              directionalShadowMap : { value : Array },
*              directionalShadowMatrix : { value : Array },
*              spotLights : { value : Array, properties : { color : *, position : *, direction : *, distance : *, coneCos : *, penumbraCos : *, decay : *}},
*              spotLightShadows : { value : Array, properties : { shadowBias : *, shadowNormalBias : *, shadowRadius : *, shadowMapSize : *}},
*              spotShadowMap : { value : Array },
*              spotShadowMatrix : { value : Array },
*              pointLights : { value : Array, properties : { color : *, position : *, direction : *, distance : *}},
*              pointLightShadows : { value : Array, properties : { shadowBias : *, shadowNormalBias : *, shadowRadius : *, shadowMapSize : *, shadowCameraNear : *, shadowCameraFar : *}},
*              pointShadowMap : { value : Array },
*              pointShadowMatrix : { value : Array },                
*              hemisphereLights : { value : Array, properties : { direction : *, skyColor : *, groundColor : *}},
*              rectAreaLights : { value : Array, properties :  { color : *, position : *, width : *, height : *}},
*              ltc_1 : { value : * },
*              ltc_2 : { value : * },  
*              sprite : { diffuse : {value : Color }, opacity : {value : number }, center : {value : Vector2 }, rotation : {value : number }, map : {value : * }, alphaMap : {value : * }, uvTransform : { value : Matrix3 }, },  
*              farDistance : { value : number},
*              nearDistance : { value : number},
*              referencePosition : {value : Vector3 },
*              halfWidth : Vector3,
*              halfHeight : Vector3,
*              clearcoatNormalScale : {value : Vector2 },
*              shininess : { value : number},
*              roughness : { value : number},
*              metalness : { value : number},
*              scale : { value : number},
*              envMapIntensity : { value : number},
*              emissive : {value : Color },
*              specular : { value : Color},
*              skyColor : Color,
*              groundColor : Color,
*              color : { value : Color },
*              sheen : {value : Color },
*              rotation : number,
*              decay : number,
*              direction : Vector3,
*              position : Vector3,
*              dashSize : { value : number},
*              totalSize : { value : number},
*              clearcoat : { value : number},
*              clearcoatRoughness : { value : number},
*              transmission : { value : number},
*              distance : number,
*              clearcoatMap : (undefined|{value: *}),
*              clearcoatRoughnessMap : (undefined|{value: *}),
*              matcap : (undefined|{value: *}),
*              t2D : (undefined|{value: *}),
*              tEquirect : (undefined|{value: *}),
*              clearcoatNormalMap : (undefined|{value: *}),
*              transmissionMap : (undefined|{value: *}),
*              map : (undefined|{value: *}),
              
}
*          } 
*/
var UniformInterface;

export { UniformInterface };